/**
 * Tests for the Migrator (.env → .envora conversion).
 */

import { Migrator } from '../src/migrate/Migrator.js';

const migrator = new Migrator();

function migrate(source) {
  return migrator._convert(source);
}

describe('Migrator', () => {
  test('converts simple KEY=value', () => {
    const result = migrate('PORT=3000\n');
    expect(result).toContain('PORT: 3000');
  });

  test('converts string value with quotes', () => {
    const result = migrate('APP_NAME=My Application\n');
    expect(result).toContain('"My Application"');
  });

  test('groups keys with common prefix into sections', () => {
    const result = migrate('DATABASE_HOST=localhost\nDATABASE_PORT=5432\n');
    expect(result).toContain('DATABASE {');
    expect(result).toContain('host:');
    expect(result).toContain('port:');
    expect(result).toContain('}');
  });

  test('converts boolean strings as-is', () => {
    const result = migrate('DEBUG=true\n');
    expect(result).toContain('true');
  });

  test('converts numeric strings as numbers', () => {
    const result = migrate('PORT=8080\n');
    expect(result).toContain('8080');
    // Should not be quoted as a string
    expect(result).not.toMatch(/PORT: "8080"/);
  });

  test('preserves non-grouped keys at root level', () => {
    const result = migrate('SOLO=value\n');
    expect(result).toContain('SOLO: "value"');
  });

  test('skips .env comment lines', () => {
    const result = migrate('# comment\nPORT=3000\n');
    expect(result).not.toContain('# comment\nPORT'); // comment should not be in key
    expect(result).toContain('PORT: 3000');
  });

  test('handles empty .env', () => {
    const result = migrate('');
    expect(typeof result).toBe('string');
  });

  test('generates valid header comment', () => {
    const result = migrate('PORT=3000\n');
    expect(result).toContain('# Generated by envora migrate');
  });

  test('converts multiple sections', () => {
    const result = migrate(
      'DATABASE_HOST=localhost\nDATABASE_PORT=5432\n' +
      'REDIS_HOST=localhost\nREDIS_PORT=6379\n'
    );
    expect(result).toContain('DATABASE {');
    expect(result).toContain('REDIS {');
  });

  test('converts camelCase sub-keys', () => {
    // DATABASE_HOST → host (lowercase)
    const result = migrate('DATABASE_HOST=localhost\nDATABASE_PORT=5432\n');
    expect(result).toContain('host:');
    expect(result).toContain('port:');
  });
});
