/**
 * @fileoverview Migrator — converts .env files to .envora format.
 *
 * Groups flat KEY=VALUE pairs into sections when they share a common prefix,
 * e.g. DATABASE_HOST and DATABASE_PORT → DATABASE { host: "..." port: ... }
 */

import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { DotenvLoader } from '../loaders/DotenvLoader.js';
import { LoadError } from '../errors/EnvoraError.js';

export class Migrator {
  /**
   * Reads a .env file and returns a .envora-formatted string.
   *
   * @param {string} envFilePath - Path to the .env file
   * @returns {Promise<string>} - The generated .envora source
   */
  async migrate(envFilePath) {
    const resolved = path.resolve(envFilePath);
    let source;

    try {
      source = await readFile(resolved, 'utf8');
    } catch (err) {
      throw new LoadError(`Cannot read file: ${resolved}`, {
        file: resolved,
        cause: err,
      });
    }

    return this._convert(source);
  }

  /**
   * Converts .env source text to .envora source text.
   * @param {string} envSource
   * @returns {string}
   */
  _convert(envSource) {
    const loader = new DotenvLoader();
    const ctx = loader.parse(envSource);
    const raw = ctx.toRawObject();

    // Group keys by prefix (e.g. DATABASE_HOST → DATABASE section)
    const sections = this._groupByPrefix(raw);

    const lines = [
      '# Generated by envora migrate',
      '# Review and adjust as needed',
      '',
    ];

    for (const [sectionName, entries] of Object.entries(sections)) {
      if (Object.keys(entries).length === 1 && sectionName === '__root__') {
        // Single ungrouped entry
        const [[k, v]] = Object.entries(entries);
        lines.push(`${k}: ${this._formatValue(v)}`);
      } else if (sectionName === '__root__') {
        for (const [k, v] of Object.entries(entries)) {
          lines.push(`${k}: ${this._formatValue(v)}`);
        }
      } else {
        lines.push(`${sectionName} {`);
        for (const [k, v] of Object.entries(entries)) {
          lines.push(`    ${k}: ${this._formatValue(v)}`);
        }
        lines.push('}');
        lines.push('');
      }
    }

    return lines.join('\n').trimEnd() + '\n';
  }

  /**
   * Groups flat KEY=VALUE pairs by common uppercase prefix.
   * e.g. DATABASE_HOST, DATABASE_PORT → { DATABASE: { host, port } }
   *      PORT, DEBUG → { __root__: { PORT, DEBUG } }
   *
   * @param {Record<string,string>} flat
   * @returns {Record<string, Record<string,string>>}
   */
  _groupByPrefix(flat) {
    const groups = {};
    const prefixCount = {};

    // Count how many keys share each prefix
    for (const key of Object.keys(flat)) {
      const underIdx = key.indexOf('_');
      if (underIdx > 0) {
        const prefix = key.slice(0, underIdx);
        prefixCount[prefix] = (prefixCount[prefix] ?? 0) + 1;
      }
    }

    for (const [key, value] of Object.entries(flat)) {
      const underIdx = key.indexOf('_');
      const prefix = underIdx > 0 ? key.slice(0, underIdx) : null;

      if (prefix && prefixCount[prefix] > 1) {
        // Group this under the prefix section
        const subKey = this._toCamelCase(key.slice(underIdx + 1));
        if (!groups[prefix]) groups[prefix] = {};
        groups[prefix][subKey] = value;
      } else {
        // No grouping — put at root
        if (!groups['__root__']) groups['__root__'] = {};
        groups['__root__'][key] = value;
      }
    }

    return groups;
  }

  /**
   * Converts SNAKE_CASE to camelCase.
   * e.g. "HOST_NAME" → "hostName"
   */
  _toCamelCase(str) {
    return str
      .toLowerCase()
      .replace(/_([a-z])/g, (_, c) => c.toUpperCase());
  }

  /**
   * Formats a string value for .envora output.
   * Detects if it should be a number, boolean, or string.
   */
  _formatValue(value) {
    if (value === 'true' || value === 'false') return value;

    const n = Number(value);
    if (value !== '' && !isNaN(n)) return String(n);

    // Escape double quotes in strings
    const escaped = value.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
    return `"${escaped}"`;
  }
}
